import 'dart:io';

import 'package:fritz_tr064/fritz_tr064.dart';

/// Discover the default username without authentication, then prompt for
/// credentials interactively to verify they work.
///
/// Run with: dart run example/default_user_example.dart
void main() async {
  // 1. Prompt for Fritz!Box host
  stdout.write('Fritz!Box host [192.168.178.1]: ');
  final hostInput = stdin.readLineSync()?.trim() ?? '';
  final host = hostInput.isEmpty ? '192.168.178.1' : hostInput;

  // 2. Connect without credentials to discover users
  print('\nConnecting to $host without authentication...');
  final anonClient = Tr64Client(
    host: host,
    username: '',
    password: '',
  );

  String? defaultUsername;
  try {
    await anonClient.connect();

    final security = anonClient.lanConfigSecurity();
    if (security == null) {
      print('LANConfigSecurity service not available on this device.');
      return;
    }

    // 3. Discover the default username (no auth required)
    defaultUsername = await security.getDefaultUsername();
    print('Default username: ${defaultUsername ?? '(none)'}');

    final users = await security.getUserList();
    if (users.isNotEmpty) {
      print('\nRegistered users:');
      for (final user in users) {
        final markers = <String>[];
        if (user.lastUser) markers.add('last login');
        if (user.isAutoGenerated) markers.add('auto-generated');
        final suffix = markers.isEmpty ? '' : ' (${markers.join(', ')})';
        print('  - ${user.username}$suffix');
      }
    }
  } finally {
    anonClient.close();
  }

  // 4. Prompt for credentials
  final defaultUser = defaultUsername ?? '';
  stdout.write('\nUsername [$defaultUser]: ');
  final userInput = stdin.readLineSync()?.trim() ?? '';
  final username = userInput.isEmpty ? defaultUser : userInput;

  stdout.write('Password: ');
  stdin.echoMode = false;
  final password = stdin.readLineSync()?.trim() ?? '';
  stdin.echoMode = true;
  print(''); // newline after hidden input

  if (username.isEmpty || password.isEmpty) {
    print('Username and password are required.');
    return;
  }

  // 5. Connect with credentials
  print('Authenticating as $username...');
  final authClient = Tr64Client(
    host: host,
    username: username,
    password: password,
  );

  try {
    await authClient.connect();

    final security = authClient.lanConfigSecurity();
    if (security == null) {
      print('LANConfigSecurity service not available on this device.');
      return;
    }

    // 6. Call an authenticated action to prove the credentials work
    final CurrentUser currentUser;
    try {
      currentUser = await security.getCurrentUser();
    } on SoapFaultException catch (e) {
      print('Authentication failed: ${e.faultString}');
      return;
    }
    print('Authenticated as: ${currentUser.username}');

    // 7. Print the user's rights
    if (currentUser.rights.isNotEmpty) {
      print('\nRights:');
      for (final right in currentUser.rights) {
        print('  ${right.path}: ${right.access}');
      }
    }
  } finally {
    authClient.close();
  }
}
